export const languages = Object.freeze({
  english: {
    tabs: {
      home: 'Home',
      complaints: 'Complaints',
      settings: 'Settings',
    },
    splashScreen: {
      title: 'Choose Language',
      description:
        'Select in which Language you would like to use the Application.',
      buttonLabel: 'Continue',
    },
    onBoardingScreen: {
      text1: 'Give us good information on time.',
      text2: 'Our personnel will take care of it.',
      text3: 'You will then receive a response from us in no time.',
      previous: 'Previous',
      next: 'Next',
      getStarted: 'Get Started',
    },
    homeScreen: {
      button: 'Complain Now',
    },
    complaintsScreen: {
      title: 'Follow Complaint',
      phoneTitle: 'What is your phone number?',
      phonePlaceholder: 'Phone Number',
      complaintTitle: 'What is the complaint number?',
      complaintPlaceholder: 'Complaint Number',
      buttonLabel: 'Search',
    },
    complaintDetailsScreen: {
      title: 'Complaint Details',
      complaintNumber: 'Complaint Number',
      phoneNumber: 'Phone Number',
      description: 'Description',
      status: 'Status',
      idNumber: 'ID Number',
      buSector: 'Business Sector',
      comNames: 'Commodities Names',
      borderLocation: 'Border Location',
      comment: 'Comment',
      complainant:'Complainant Nationality'
    },
    settingsScreen: {
      language: 'Change Language',
      aboutUs: 'About Us',
    },
    settingsLanguageScreen: {
      title: 'Choose Language',
      description:
        'Select in which language you would like to use the application',
      buttonLabel: 'Change',
    },
    aboutUsScreen: {
      title: 'About Us',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
    newComplaintScreen: {
      title: 'New Complaint',
      phoneLabel: 'What is your Phone Number?',
      phonePlaceholder: 'Phone Number',
      idLabel: 'What is your ID Number?',
      idPlaceholder: 'ID Number',
      genderLabel: 'How about your gender?',
      male: 'Male',
      female: 'Female',
      categoryLabel: 'What is the complaint category?',
      selectLabel: 'Select Category',
      countryLabel: 'What is your Nationality?',
      selectCountryLabel: 'Select Nationality',
      buSectorLabel: 'What is the Business Sector?',
      selectBuSectorLabel: 'Select Business Sector',
      borderLocationLabel: 'What is the Border Location?',
      selectBorderLocationLabel: 'Select Border Location',
      searchLabel: 'Search Category',
      comNamesLabel: 'Commodities Names?',
      comNamesPlaceholder: 'commodities names',
      messageLabel: 'What happened?',
      messagePlaceholder: 'Message',
      notificationLabel: 'How would you like to be notified?',
      emailLabel: 'What is your email?',
      emailPlaceholder: 'Email',
      documentLabel: 'Do you want to upload supporting documents?',
      documentOptional: 'Optional',
      fileNum: 'file',
      uploadBtn: 'Upload',
      button: 'Send',
    },
    successScreen: {
      text: `We've successfully received your complaint. We will get back to you shortly.`,
      button: 'Back Home',
    },
    errorMessage: {
      phoneNumber: 'Phone Number is required',
      wrongPhoneNumber: 'Phone Number is invalid',
      gender: 'Gender is required',
      category: 'Category is required',
      country: 'Country is required',
      message: 'Message is required',
      notification: 'Select at least one way to get notified',
      email: 'Email is required',
      wrongEmail: 'Email is invalid',
      complaintNo: 'Complaint Number is required',
      notFound: 'Sorry ,your record can not be found in database',
      idNumber: 'Id number is required',
      wrongIdNumber: 'Id number can not be less than 16',
      buSector: 'Business Sector is required',
      comNames: 'Commodities Names is required',
      borderLocation: 'Border Location is required',
    },
  },
  kinyarwanda: {
    tabs: {
      home: 'Ahabanza',
      complaints: 'Ibirego',
      settings: 'Igenamiterere',
    },
    splashScreen: {
      title: 'Hitamo Ururimi',
      description: 'Hitamo ururimi wifuza gukoresha.',
      buttonLabel: 'Komeza',
    },
    onBoardingScreen: {
      text1: 'Tanga amakuru yizewe kandi ku gihe.',
      text2: 'Abakozi bacu baragufasha kubikurikirana.',
      text3: 'Mu gihe gito ukabona igisubizo',
      previous: 'Inyuma',
      next: 'Imbere',
      getStarted: 'Tangira',
    },
    homeScreen: {
      button: 'Tangira',
    },
    complaintsScreen: {
      title: 'Kurikirana Ikirego',
      phoneTitle: 'Numero ya telephone yawe?',
      phonePlaceholder: 'Numero ya telephone',
      complaintTitle: `Numer y'ikirego cyawe?`,
      complaintPlaceholder: `Numero y'ikirego`,
      buttonLabel: 'Shakisha',
      comNames: `Amazina y'Ibicuruzwa`,
      borderLocation: 'Umupaka',
      comment: 'Igisubizo',
      complainant:`Ubwenegihugu bw'urega`
    },
    complaintDetailsScreen: {
      title: 'Ibisobanuro birambuye',
      complaintNumber: `Numero y'ikirego`,
      phoneNumber: 'Numero ya telephone',
      description: 'Ibisobanuro',
      status: 'Imiterere',
      idNumber: `Numero y'Indangamuntu`,
      buSector: `Urwego rw' Ubucuruzi`,
    },
    settingsScreen: {
      language: 'Hindura Ururimi',
      aboutUs: 'Turi bande',
    },
    settingsLanguageScreen: {
      title: 'Hindura Ururimi',
      description: 'Hitamo ururimi wifuza kujya ukoresha',
      buttonLabel: 'Hindura',
    },
    aboutUsScreen: {
      title: 'Turi bande',
      description:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    },
    newComplaintScreen: {
      title: 'Ikirego Gishya',
      phoneLabel: 'Numero ya telephone',
      phonePlaceholder: 'Numero ya telephone',
      idLabel: `Numero y'indangamuntu`,
      idPlaceholder: `Numero y'indangamuntu`,
      genderLabel: 'Igitsina',
      male: 'Gabo',
      female: 'Gore',
      categoryLabel: `Icyiciro cy' Ikirego`,
      selectLabel: 'Hitamo Icyiciro',
      countryLabel: 'Ubwenegihugu',
      selectCountryLabel: 'Hitamo ubwenegihugu',
      buSectorLabel: `Urwego rw'ubucuruzi`,
      selectBuSectorLabel: `Hitamo urwego rw'ubucuruzi`,
      borderLocationLabel: 'Hitamo Umupaka',
      selectBorderLocationLabel: 'Hitamo Umupaka',
      searchLabel: 'Hitamo Icyiciro',
      comNamesLabel: 'Ibicuruzwa',
      comNamesPlaceholder: 'Ibicuruzwa',
      messageLabel: 'Ikirego',
      messagePlaceholder: 'ikirego',
      notificationLabel: 'Murifuza kumenyeshwa gute?',
      emailLabel: 'Email',
      emailPlaceholder: 'Email',
      documentLabel: 'Waba ufite dosiye wifuza kwohereza?',
      documentOptional: 'si itegeko',
      fileNum: 'dosiye',
      uploadBtn: 'Dosiye',
      button: 'Ohereze',
    },
    successScreen: {
      text: 'Murakoze, Twakiriye ikirego cyanyu neza.',
      button: 'Subira Ahabanza',
    },
    errorMessage: {
      phoneNumber: 'Nimero ya telephone irakenewe',
      wrongPhoneNumber: 'Imibare ya nimero ya telephone ntiyuzuye',
      gender: 'Hitamo igitsina cyawe',
      category: `Hitamo icyiciro cy'Ikirego`,
      country: `Hitamo ubwenegihugu`,
      message: 'Andika Ikirego',
      notification: 'Hitamo uburyo nibura bumwe mwifuza kumenyeshwamo',
      email: 'Email yanyu irakenewe',
      wrongEmail: 'email ntiyemewe',
      complaintNo: 'Nimero y ikirego irakenewe',
      notFound: 'Ihangane, Ikirego cyawe ntikibashije kuboneka',
      idNumber: `Numero y' indangamuntu irakenewe`,
      wrongIdNumber: `Numero y' indangamuntu ntirenza imibare 16`,
      buSector: `Hitamo urwego rw'ubucuruzi`,
      comNames: 'Ibicuruzwa birakenewe',
      borderLocation: 'Hitamo Umupaka',
    },
  },
});
